import type { AssetClass, BuildingType, EventLayer, Level, LevelConfig } from "./types";

const ALL_ASSETS: AssetClass[] = [
  "deposit",
  "bond",
  "etf",
  "realestate",
  "gold",
  "oil",
  "fx",
  "crypto",
];

const ALL_BUILDINGS: BuildingType[] = [
  "factory",
  "rnd",
  "office",
  "warehouse",
  "store",
  "power",
  "hr",
  "park",
  "cafeteria",
  "dorm",
  "gym",
  "daycare",
  "clinic",
  "lab",
];

const ALL_LAYERS: EventLayer[] = [
  "macro",
  "monetary",
  "geopolitics",
  "intercompany",
  "internal",
  "market",
  "visitor",
];

export const LEVEL_CONFIGS: Record<Level, LevelConfig> = {
  elementary_low: {
    level: "elementary_low",
    label: "초등 1~2학년",
    description: "물건을 만들고 팔며 돈을 모으는 기본 흐름을 익혀요.",
    recommendedAge: "초등 1~2학년",
    mapSize: 5,
    instantBuild: true,
    adjacencyBonus: false,
    startingCash: 1_000_000,
    volatility: 0.25,
    eventIntensity: 0.25,
    enabledAssets: ["deposit"],
    enabledBuildings: ["factory", "store", "office", "park"],
    enabledEventLayers: ["market", "visitor"],
    showAdvancedMetrics: false,
    characterDepth: "simple",
    simplifiedLabels: true,
    maxChoices: 2,
    numberScale: "small",
    feedbackDepth: "picture",
    aiCount: 2,
    bankruptcyPolicy: "bailout",
  },
  elementary_mid: {
    level: "elementary_mid",
    label: "초등 3~4학년",
    description: "수입, 지출, 예산을 구분하며 가게를 운영해요.",
    recommendedAge: "초등 3~4학년",
    mapSize: 6,
    instantBuild: true,
    adjacencyBonus: false,
    startingCash: 850_000,
    volatility: 0.4,
    eventIntensity: 0.45,
    enabledAssets: ["deposit", "bond"],
    enabledBuildings: ["factory", "store", "office", "park", "cafeteria"],
    enabledEventLayers: ["macro", "market", "visitor"],
    showAdvancedMetrics: false,
    characterDepth: "simple",
    simplifiedLabels: false,
    maxChoices: 3,
    numberScale: "medium",
    feedbackDepth: "simple",
    aiCount: 8,
    bankruptcyPolicy: "bailout",
  },
  elementary_high: {
    level: "elementary_high",
    label: "초등 5~6학년",
    description: "매출, 비용, 이익, 재고를 함께 보며 회사를 키워요.",
    recommendedAge: "초등 5~6학년",
    mapSize: 7,
    instantBuild: true,
    adjacencyBonus: false,
    startingCash: 750_000,
    volatility: 0.55,
    eventIntensity: 0.6,
    enabledAssets: ["deposit", "bond", "etf"],
    enabledBuildings: ["factory", "rnd", "store", "office", "warehouse", "park", "cafeteria", "daycare"],
    enabledEventLayers: ["macro", "market", "internal", "visitor"],
    showAdvancedMetrics: false,
    characterDepth: "simple",
    simplifiedLabels: false,
    maxChoices: 3,
    numberScale: "large",
    feedbackDepth: "reason",
    aiCount: 16,
    bankruptcyPolicy: "bailout",
  },
  middle: {
    level: "middle",
    label: "중학생",
    description: "수요, 공급, 금리, 기회비용을 고려하며 전략을 세워요.",
    recommendedAge: "중학생",
    mapSize: 8,
    instantBuild: false,
    adjacencyBonus: true,
    startingCash: 650_000,
    volatility: 0.9,
    eventIntensity: 0.9,
    enabledAssets: ["deposit", "bond", "etf", "realestate", "gold", "oil"],
    enabledBuildings: ["factory", "rnd", "office", "warehouse", "store", "hr", "park", "cafeteria", "dorm", "gym", "daycare", "clinic"],
    enabledEventLayers: ["macro", "monetary", "geopolitics", "intercompany", "internal", "market", "visitor"],
    showAdvancedMetrics: true,
    characterDepth: "roles",
    simplifiedLabels: false,
    maxChoices: 4,
    numberScale: "advanced",
    feedbackDepth: "reason",
    aiCount: 20,
    bankruptcyPolicy: "strict",
  },
  high: {
    level: "high",
    label: "고등학생",
    description: "현금, 부채, 수익률, 시장 국면을 분리해 판단해요.",
    recommendedAge: "고등학생",
    mapSize: 9,
    instantBuild: false,
    adjacencyBonus: true,
    startingCash: 580_000,
    volatility: 1.15,
    eventIntensity: 1.15,
    enabledAssets: ["deposit", "bond", "etf", "realestate", "gold", "oil", "fx"],
    enabledBuildings: ALL_BUILDINGS,
    enabledEventLayers: ALL_LAYERS,
    showAdvancedMetrics: true,
    characterDepth: "roles",
    simplifiedLabels: false,
    maxChoices: 4,
    numberScale: "advanced",
    feedbackDepth: "analysis",
    aiCount: 24,
    bankruptcyPolicy: "strict",
  },
  adult: {
    level: "adult",
    label: "대학생·성인",
    description: "자본 배분, 포트폴리오, 복합 이벤트까지 모두 활용해요.",
    recommendedAge: "대학생·성인",
    mapSize: 10,
    instantBuild: false,
    adjacencyBonus: true,
    startingCash: 500_000,
    volatility: 1.5,
    eventIntensity: 1.4,
    enabledAssets: ALL_ASSETS,
    enabledBuildings: ALL_BUILDINGS,
    enabledEventLayers: ALL_LAYERS,
    showAdvancedMetrics: true,
    characterDepth: "full",
    simplifiedLabels: false,
    maxChoices: 5,
    numberScale: "advanced",
    feedbackDepth: "analysis",
    aiCount: 28,
    bankruptcyPolicy: "strict",
  },
};

export function getLevelConfig(level: Level): LevelConfig {
  return LEVEL_CONFIGS[level];
}
